---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agnostics
  labels:
    {{- include "scheduler.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: agnostics
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        name: agnostics
    spec:
      containers:
        - name: agnostics
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GIT_URL
              value: {{ .Values.git.url }}
            - name: GIT_SSH_PRIVATE_KEY
              value: {{ .Values.git.private_key }}
            - name: REDIS_URL
              value: {{ .Values.git.redis_url }}
            - name: DEBUG
              value: {{ .Values.git.debug }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: agnostics-baylon-secret
              mountPath: /.ssh

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: agnostics-baylon-secret
          secret:
            secretName: agnostics-baylon
