---
apiVersion: v1
kind: Secret
metadata:
  name: scheduler-baylon
type: Opaque
data:
  id_rsa: |-
    {{ .Files.Get "files/id_rsa" | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.name }}
type: Opaque
data:
  #database-password: |-
  # {{ randAlphaNum 20 | b64enc }}
  database-password: ZG5Cdk9vczRYRDAwTmhJTg==

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.redis.name }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2

